server:
  port: 1211
spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: resource-service
          uri: lb://RESOURCESERVICE
          predicates:
          - Path=/resources/**
        - id: song-service
          uri: lb://SONGSERVICE
          predicates:
          - Path=/songs/**
        - id: storage-service
          uri: lb://STORAGESERVICE
          predicates:
            - Path=/storages/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
